### ISSUE TITLE
🪲 Bug Report - policy assignments exceed 4MB

### ISSUE THREAD

**Issue by kasimrehman** [Azure/ALZ-Bicep#833] opened 2024-08-28 13:27 UTC
## Describe the bug

When deploying the built-in custom policy assignments the error message "Error: Code=RequestContentTooLarge; Message=The request content size exceeds the maximum size of 4 MB." is shown.

## To Reproduce
Update the parameters file of the module by changing the management group prefix, region, resource id for the existing LAW, three DCRs and the UMI, and the security contact.

## Expected behaviour

The deployment returns with a success message

## Screenshots 📷

![image](https://github.com/user-attachments/assets/528419d9-d394-4af5-8cc9-ccb9be8f9b78)

**Comment by jtracey93** [comment] 2024-08-28 13:59
Closing as duplicate of https://github.com/Azure/ALZ-Bicep/issues/821

**Closed by jtracey93** 2024-08-28 13:59 UTC
