### ISSUE TITLE
Option to add subnets to spoke vnet

### ISSUE THREAD

**Issue by kmridha92** [Azure/ALZ-Bicep#767] opened 2024-04-17 00:31 UTC
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

This module "infra-as-code/bicep/orchestration/hubPeeredSpoke/hubPeeredSpoke.bicep" calls "infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.bicep" for setting up spoke vnet. There is no option to add subnet like in "infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep"

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

As subnets can not be added while creating vnet, every time I re-run this via pipeline it removes the subnets that were created later on the vnet. It would be easier if there is an option to add subnet like there is in hubNetworking module.

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Can you describe any alternatives that you have taken since this feature does not exist?

I have a seperate custom module that creates the subnets but the re-run of spokeNetworking module with pipeline removes them.

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment] 2024-04-17 22:05
Hi @kmridha92, this looks to be a duplicate of issue #301. We also have the following[ disclaimer ](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/spokeNetworking/README.md#note)within the spokeNetwork module as well, which provides insight into why we won't be adding subnets to the module. Along with that, we recommend looking into the [Bicep LZ Vending Modul](https://github.com/Azure/bicep-lz-vending)e to handle the spoke networking as well as quite a bit more for setting up the application landing zone subscriptions. 

I'd highly recommend looking at Azure Verified modules if you don't want to have to worry about creating your own module, or if you do would like to manage your own module, please take a look at this this [Tech Community blog](https://www.bing.com/search?q=azure+subnet+api+versions&qs=n&form=QBRE&sp=-1&ghc=1&lq=0&pq=azure+subnet+api+version&sc=6-24&sk=&cvid=334AE11D2F2C4D9F91AEDD2B0BE73816&ghsh=0&ghacc=0&ghpl=) as well as this [GitHub Issue](https://github.com/Azure/azure-quickstart-templates/issues/2786) to better understand work that the Azure networking team is doing to support updates to virtual networks without the subnet property.

**Closed by oZakari** 2024-04-17 22:05 UTC
Labels: enhancement
