### ISSUE TITLE
Custom policies and policy set definitions - optimal module location

### ISSUE THREAD

**Issue by danadamsituk** [Azure/ALZ-Bicep#774] opened 2024-04-23 17:21 UTC
I'm looking to implement custom policies and policy initiatives with ALZ-Bicep following best practice but am unsure how best to handle the policy module.

As we’re directly modifying the lib directory, should the entire policy module be copied to custom-modules to prevent issues around ALZ-Bicep update, or is there a more sensible approach to take, perhaps keeping the custom policy/policy set definitions within the config folder somehow?

**Comment by oZakari** [comment] 2024-04-23 20:34
Hi @danadamsituk, this appears to be a duplicate of #646 which I am working on and expecting to hopefully complete next month. I am planning on moving the policy module directory in its entirety to the custom-modules directory by default and then essentially updating the scripts and workflows/pipelines referenced within this [documentation](https://github.com/Azure/ALZ-Bicep/wiki/PolicyDeepDive#what-azure-policies-does-azure-landing-zone-enterprise-scale-provide-additionally-to-those-already-built-in). That way you can extend the policies you need to modify on your end and get the latest policies from [Enterprise-Scale](https://github.com/Azure/Enterprise-Scale/) repo which is what ALZ-Bicep syncs with. Still a work in progress though, so some of that may change somewhat. 

Will go ahead and close this to have a single issue open. Please feel free to bring forth additional questions or offer any other insight on that thread.

**Closed by oZakari** 2024-04-23 20:34 UTC
